/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kimlong
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private static final String dataConn="jdbc:mysql://localhost:3306/jdbcdemo";
    private static final String username="root";
    private static final String password="";
    Connection sqlConn = null;
    PreparedStatement pst= null;
    ResultSet rs=null;
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRegister = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtextUsername2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtextEmail2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jbtnRegister = new javax.swing.JButton();
        jlabelLogin = new javax.swing.JLabel();
        jlabelWarning2 = new javax.swing.JLabel();
        jtextPassword2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jtextConfirm = new javax.swing.JPasswordField();
        asAdmin = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanelRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jpanelRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(122, 122, 122))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        jpanelRegister.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 390, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("Username: ");

        jtextUsername2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtextUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextUsername2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setText("Email:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setText("Password:");

        jtextEmail2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtextEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextEmail2ActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));

        jbtnRegister.setBackground(new java.awt.Color(255, 0, 51));
        jbtnRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnRegister.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRegister.setText("REGISTER");
        jbtnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterActionPerformed(evt);
            }
        });

        jlabelLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabelLogin.setForeground(new java.awt.Color(0, 153, 255));
        jlabelLogin.setText("Back");
        jlabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelLoginMouseClicked(evt);
            }
        });

        jlabelWarning2.setForeground(new java.awt.Color(255, 0, 51));

        jtextPassword2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Confirm Password:");

        jtextConfirm.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        asAdmin.setText("Register as admin");
        asAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(asAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtextConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(65, 65, 65)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtextEmail2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(jtextUsername2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtextPassword2)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jlabelWarning2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jlabelLogin))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jbtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtextUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtextEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtextPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtextConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(asAdmin)))
                .addGap(18, 18, 18)
                .addComponent(jlabelWarning2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jbtnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jpanelRegister.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 390, 440));

        getContentPane().add(jpanelRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelLoginMouseClicked
        // TODO add your handling code here:
        new Setting().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlabelLoginMouseClicked

    private void jbtnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegisterActionPerformed
        // TODO add your handling code here:
        jlabelWarning2.setText("");
        boolean isEmailUsed=false;
        try {
            /**
             * check : require information is filled or not
             */
            if(!(jtextUsername2.getText().isEmpty() || jtextEmail2.getText().isEmpty() || jtextPassword2.getPassword().length==0 || jtextConfirm.getPassword().length==0)) {
                /**
                 * check : email address is correct or not.
                 */
                if(jtextEmail2.getText().contains("@gmail.com") || jtextEmail2.getText().contains("@outlook.com") ) {
                    /**
                     * check : email address is already used or not
                     */
                    try{
                        Class.forName("com.mysql.cj.jdbc.Driver");
                        sqlConn = DriverManager.getConnection(dataConn,username,password);
                        String sql="select * from user";
                        pst = sqlConn.prepareStatement(sql);

                        rs = pst.executeQuery();

                        while(rs.next()){
                            if(jtextEmail2.getText().compareTo(rs.getString("email"))==0){
                                isEmailUsed=true;
                                break;
                            }
                        }

                    }catch(Exception ex){
                        JOptionPane.showMessageDialog(null,ex);
                    }
                    /**
                     * if an email is not used yet.
                     */
                    if(!isEmailUsed) {

                        if (jtextPassword2.getPassword().length >= 8) {
                            if (jtextPassword2.getText().compareTo(jtextConfirm.getText()) == 0) {

                                Class.forName("com.mysql.cj.jdbc.Driver");
                                sqlConn = DriverManager.getConnection(dataConn, username, password);
                                pst = sqlConn.prepareStatement("insert into user(username,email,password,admin)value(?,?,?,?)");
                                int admin=0;
                                if (asAdmin.getText()!= "-1"){
                                    admin=1;
                                }
                                pst.setString(1, jtextUsername2.getText());
                                pst.setString(2, jtextEmail2.getText());
                                pst.setString(3, jtextPassword2.getText());
                                pst.setInt(4, admin);

                                pst.executeUpdate();

                                JOptionPane.showMessageDialog(this, "You have registered successfully!!!");

                                new Setting().setVisible(true);
                                this.setVisible(false);
                            } else {
                                jlabelWarning2.setText("Your password does not match !!! Please try again...");
                                jtextConfirm.setText("");
                            }
                        } else {
                            jlabelWarning2.setText("Your password isn't strong enough!!! (at least 8 characters)");
                            jtextPassword2.setText("");
                            jtextConfirm.setText("");
                        }
                    }else {
                        jlabelWarning2.setText("Your email address is already used!!! Please try again...");
                    }
                }else {
                    jlabelWarning2.setText("Your email address is not correct!!! Please try again...");
                }
            }else {
                JOptionPane.showMessageDialog(this, "Please input all the information!!!");
            }

        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jbtnRegisterActionPerformed

    private void jtextEmail2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextEmail2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextEmail2ActionPerformed

    private void jtextUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextUsername2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnRegister;
    private javax.swing.JLabel jlabelLogin;
    private javax.swing.JLabel jlabelWarning2;
    private javax.swing.JPanel jpanelRegister;
    private javax.swing.JPasswordField jtextConfirm;
    private javax.swing.JTextField jtextEmail2;
    private javax.swing.JPasswordField jtextPassword2;
    private javax.swing.JTextField jtextUsername2;
    // End of variables declaration//GEN-END:variables
}
